# Generated by Django 2.2.16 on 2022-09-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created', 'author'], 'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
    ]
